In [8]:
import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

1.9.0


In [5]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [16]:
addition = a + b
mult = a * b

In [22]:
mat_a = np.random.uniform(0,1,(4,4))
mat_b = np.random.uniform(0,1,(4,4))

In [27]:
with tf.Session() as sess:
    multi = sess.run(mult , feed_dict = {a:mat_a , b:mat_b})
    add = sess.run(addition , feed_dict = {a:mat_a , b:mat_b})

In [28]:
mat_a

array([[0.70900604, 0.34274075, 0.37810498, 0.56639318],
       [0.63886715, 0.79596048, 0.88327875, 0.05192663],
       [0.96930903, 0.06342309, 0.59497196, 0.05718683],
       [0.07801077, 0.70939545, 0.35657649, 0.42073812]])

In [29]:
mat_b

array([[0.99739935, 0.45368988, 0.03194228, 0.89366468],
       [0.79141064, 0.21748523, 0.0760056 , 0.37376041],
       [0.56670851, 0.81557004, 0.32809624, 0.36919558],
       [0.80913586, 0.87374848, 0.74997732, 0.83769218]])

In [30]:
multi

array([[0.7071622 , 0.155498  , 0.01207754, 0.50616556],
       [0.50560623, 0.17310965, 0.06713413, 0.01940812],
       [0.5493157 , 0.05172596, 0.19520806, 0.02111313],
       [0.06312132, 0.61983323, 0.2674243 , 0.35244906]], dtype=float32)

In [31]:
add

array([[1.7064054 , 0.7964306 , 0.41004726, 1.4600579 ],
       [1.4302778 , 1.0134457 , 0.9592843 , 0.42568702],
       [1.5360175 , 0.87899315, 0.92306817, 0.42638242],
       [0.88714665, 1.583144  , 1.1065538 , 1.2584304 ]], dtype=float32)